# Generated by Django 3.1.12 on 2021-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('masukkan', models.CharField(max_length=200)),
                ('saran', models.CharField(max_length=200)),
            ],
        ),
    ]
