# Generated by Django 3.2.6 on 2021-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan4',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan5',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan6',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='kuesioner',
            name='Pilihan7',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
