# Generated by Django 3.1.12 on 2021-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0002_auto_20210828_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuesioner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
