# Generated by Django 3.1.12 on 2021-09-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keuangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_debit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_rekening', models.CharField(max_length=50, null=True)),
                ('jumlah', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(max_length=200)),
                ('tanggal', models.DateField(null=True)),
                ('debut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_keuangan.keuangan')),
            ],
        ),
    ]
