# Generated by Django 3.1.12 on 2021-09-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_keuangan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uang',
            old_name='debut',
            new_name='debit',
        ),
    ]
