# Generated by Django 3.2.6 on 2021-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('keperluan', models.CharField(max_length=100)),
            ],
        ),
    ]
