# Generated by Django 3.2.6 on 2021-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bukutamu',
            name='telepon',
            field=models.IntegerField(null=True),
        ),
    ]
