# Generated by Django 3.2.6 on 2021-08-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0003_alter_bukutamu_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukutamu',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
