# Generated by Django 3.1.12 on 2021-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0004_alter_bukutamu_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukutamu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
